export const dbName = 'internalDB';

// The first attribute is seen as a primary key
export const catAttributes = 
    `
    ANIMAL_ID,
    ORIGINAL_OWNERPOSTCODE,
    CURRENT_OWNERPOSTCODE,
    ORIGINAL_OWNERNAME,
    CURRENT_OWNERNAME,
    ANIMALTYPEID,
    ANIMALNAME,
    BREEDNAME,
    BASECOLOURID,
    MARKINGS,
    SHELTERCODE,
    DATEBROUGHTIN,
    OWNERID,
    SEX,
    IDENTICHIPNUMBER,
    AGEGROUP,
    DECEASEDDATE,
    NEUTERED,
    NEUTEREDDATE,
    ISGOODWITHCATS,
    ISGOODWITHDOGS,
    ISGOODWITHCHILDREN,
    ISHOUSETRAINED,
    ISNOTAVAILABLEFORADOPTION,
    SHELTERLOCATION,
    SIZE,
    BASECOLOUR,
    ORIGINALLAT,
    ORIGINALLNG,
    CURRENTLAT,
    CURRENTLNG,
    ORIGINAL_LATLONG,
    CURRENT_LATLONG
    `;
    